kind: CronJob
apiVersion: batch/v1beta1
metadata:
        name: mycronjob
spec:
        schedule: "* * * * *"
        jobTemplate:
                spec:
                        template:
                                spec:
                                        containers:
                                                - name: c00
                                                  image: nginx
                                                  command: ["/bin/bash", "-c", "echo Hello sai; sleep 10"]
                                        restartPolicy: Never
