kind: PersistentVolume
apiVersion: v1
metadata:
        name: mypv
spec:
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Recycle
        awsElasticBlockStore:
                volumeID: vol-05adbfe631336223e
                fsType: ext4
