kind: Pod
apiVersion: v1
metadata:
        name: testpod2
        annotations:
                description: This is a test pod
spec:
        containers:
                - name: c01
                  image: ubuntu
                  command: ["/bin/bash", "-c", "while true; do echo Hello Sai; sleep 5; done"]
