kind: ReplicaSet
apiVersion: apps/v1
metadata:
        name: myrs
spec:
        replicas: 2
        selector:
                matchExpressions:
                        - {key: myname, operator: In, values: [sai, saii, saiii]}
        template:
                metadata:
                        labels:
                                myname: sai
                spec:
                        containers:
                                - name: c00
                                  image: ubuntu
                                  command: ["/bin/bash", "-c", "while true; do echo Hello sai; sleep 10; done"]
