kind: Pod
apiVersion: v1
metadata:
        name: secret
spec:
        containers:
                - name: c00
                  image: nginx
                  command: ["/bin/bash", "-c", "while true; do echo Hello Sai; sleep 10; done"]
                  volumeMounts:
                          - name: myvol
                            mountPath: "/tmp/c1dir"
        volumes:
                - name: myvol
                  secret:
                          secretName: mysecret

               
